
project_id = "bjhpsgnovsumyvkrglgz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[api.headers]
Access-Control-Allow-Origin = "*"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
